# Generated by Django 5.1.4 on 2024-12-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppScholl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='cursos_comisiones',
            new_name='cursoscomisiones',
        ),
    ]
